apiVersion: v1
kind: Pod
metadata:
  name: hellokenobi-pod-db
  labels:
    app: hello-db
spec:
  containers:
    - name: hellokenobi-pod
      image: mysql
      ports:
        - containerPort: 3306
      envFrom:
        - configMapRef:
            name: db-configmap
