apiVersion: v1
kind: Pod
metadata:
  name: pod-pv
spec:
  containers:
    - name: nginx-pod
      image: nginx:latest
      volumeMounts:
        - mountPath: /primeiro-volume-pv
          name: primeiro-volume-pv
  volumes:
    - name: primeiro-volume-pv
      persistentVolumeClaim:
        claimName: pvc-1
